name: Build and Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image (Packaging)
      run: docker build -t ossitank/finalproject:finalproject .

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ossitank/finalproject:finalproject
